spring.application.name=kafka

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=myGroup

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.kafka.Transaction
